apiVersion: v2
appVersion: 0.0.0
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    version: ^2.0.0
description: controller to install and manage the helm.
name: installer
version: 0.0.0
